-- ==========================================
-- SNOWFLAKE SETUP - Step 4
-- Roles & Access Control
-- ==========================================

-- 1. Create custom role for pipeline
CREATE ROLE IF NOT EXISTS ECOMMERCE_ROLE
    COMMENT = 'Role for E-Commerce Data Pipeline';

-- 2. Grant database access
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE ECOMMERCE_ROLE;

-- 3. Grant schema access
GRANT USAGE ON SCHEMA ECOMMERCE_DB.RAW TO ROLE ECOMMERCE_ROLE;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.STAGING TO ROLE ECOMMERCE_ROLE;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE ECOMMERCE_ROLE;

-- 4. Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE ECOMMERCE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ECOMMERCE_DB.STAGING TO ROLE ECOMMERCE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE ECOMMERCE_ROLE;

-- 5. Grant future table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE ECOMMERCE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.STAGING TO ROLE ECOMMERCE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE ECOMMERCE_ROLE;

-- 6. Grant warehouse access
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE ECOMMERCE_ROLE;

-- 7. Assign role to your user (apna username dalo)
-- GRANT ROLE ECOMMERCE_ROLE TO USER your_username;

-- 8. Verify
SHOW GRANTS TO ROLE ECOMMERCE_ROLE;